// SPDX-FileCopyrightText: 2026 Zequinza <felipe828218@gmail.com>
// SPDX-FileCopyrightText: 2026 Whiskey Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Shared._Whiskey.Economy.Cartridge;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client._Whiskey.Economy;

/// <summary>
/// A tela da loja do PDA: saldo em cima, lista embaixo, um botão por linha.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StoreCartridgeUiFragment : BoxContainer
{
    public event Action<int>? OnComprar;

    public StoreCartridgeUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(StoreCartridgeUiState state)
    {
        SaldoLabel.Text = state.HasCard
            ? Loc.GetString("store-cartridge-balance", ("saldo", state.Balance))
            : Loc.GetString("store-cartridge-no-card");

        ListaContainer.RemoveAllChildren();

        foreach (var linha in state.Listings)
        {
            var podePagar = state.HasCard && state.Balance >= linha.Cost;
            ListaContainer.AddChild(new StoreCartridgeItem(linha, podePagar, indice => OnComprar?.Invoke(indice)));
        }
    }
}
