// SPDX-FileCopyrightText: 2026 Zequinza <felipe828218@gmail.com>
// SPDX-FileCopyrightText: 2026 Whiskey Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Trauma.Shared._Whiskey.Economy.Cartridge;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Trauma.Client._Whiskey.Economy;

/// <summary>
/// Uma linha da loja: ícone do item, nome, preço e o botão de comprar.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class StoreCartridgeItem : BoxContainer
{
    public StoreCartridgeItem(StoreCartridgeEntry linha, bool podePagar, Action<int> aoComprar)
    {
        RobustXamlLoader.Load(this);

        Icone.SetPrototype(linha.Proto);
        NomeLabel.Text = linha.Name;
        PrecoLabel.Text = linha.Cost.ToString();

        ComprarBotao.Text = Loc.GetString("store-cartridge-buy");
        // Sem saldo o botão nasce desligado. Deixar clicável e recusar depois
        // faz a pessoa clicar três vezes achando que travou.
        ComprarBotao.Disabled = !podePagar;
        ComprarBotao.OnPressed += _ => aoComprar(linha.Index);
    }
}
