// SPDX-FileCopyrightText: 2026 Whiskey Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Whiskey.NanoXp;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Whiskey.NanoXp;

[GenerateTypedNameReferences]
public sealed partial class NanoXpWindow : DefaultWindow
{
    public event Action? OnRefreshRequested;
    public event Action<string>? OnEnrollRequested;
    public event Action<string, string>? OnLoginRequested;
    public event Action? OnLogoutRequested;
    public event Action<string, string, string>? OnMailRequested;
    public event Action? OnDwaineRequested;

    public NanoXpWindow()
    {
        RobustXamlLoader.Load(this);

        DesktopButton.OnPressed += _ => ShowView(DesktopView);
        MailButton.OnPressed += _ => ShowView(MailView);
        DepartmentButton.OnPressed += _ => ShowView(DepartmentView);
        BrowserButton.OnPressed += _ => ShowView(BrowserView);
        DwaineButton.OnPressed += _ => ShowView(DwaineView);
        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
        LoginButton.OnPressed += _ => SubmitLogin();
        PasswordInput.OnTextEntered += _ => SubmitLogin();
        EnrollButton.OnPressed += _ => SubmitEnrollment();
        LogoutButton.OnPressed += _ => OnLogoutRequested?.Invoke();
        SendMailButton.OnPressed += _ => SubmitMail();
        LaunchDwaineButton.OnPressed += _ => OnDwaineRequested?.Invoke();
        Inbox.OnItemSelected += OnMailSelected;

        ShowView(DesktopView);
    }

    public void UpdateState(NanoXpUserInterfaceState state)
    {
        NetworkStatus.Text = state.Online
            ? Loc.GetString("nano-xp-online", ("network", state.NetworkName))
            : Loc.GetString("nano-xp-offline");
        Notice.Text = NoticeText(state.Notice);
        Device.Text = state.DeviceName;
        Account.Text = state.Authenticated ? state.Address : Loc.GetString("nano-xp-not-authenticated");
        Job.Text = state.Authenticated ? state.JobTitle : "-";
        Department.Text = state.Authenticated ? state.Department : "-";
        Welcome.Text = state.Authenticated
            ? Loc.GetString("nano-xp-welcome", ("name", state.DisplayName))
            : Loc.GetString("nano-xp-welcome-guest");
        DesktopHelp.Text = state.Authenticated
            ? Loc.GetString("nano-xp-desktop-help-authenticated")
            : Loc.GetString("nano-xp-desktop-help-guest");

        LoginPanel.Visible = !state.Authenticated;
        LogoutButton.Visible = state.Authenticated;
        EnrollmentHelp.Text = state.CanEnroll
            ? Loc.GetString("nano-xp-enroll-help", ("address", state.SuggestedAddress))
            : state.DeviceKind == NanoXpDeviceKind.Pda
                ? Loc.GetString("nano-xp-pda-login-help")
                : Loc.GetString("nano-xp-computer-login-help");
        EnrollButton.Visible = state.CanEnroll;
        if (!state.Authenticated && string.IsNullOrWhiteSpace(AddressInput.Text))
            AddressInput.Text = state.SuggestedAddress;

        MailButton.Disabled = !state.Authenticated;
        DepartmentButton.Disabled = !state.Authenticated;
        BrowserButton.Disabled = !state.Authenticated;
        DwaineButton.Disabled = !state.Authenticated;
        PopulateInbox(state.Inbox);
        PopulateDirectory(state.Directory);

        DepartmentAccess.Text = state.DepartmentAuthorized
            ? Loc.GetString("nano-xp-department-access-granted")
            : Loc.GetString("nano-xp-department-access-denied");
        DepartmentIdentity.Text = Loc.GetString(
            "nano-xp-department-identity",
            ("department", state.Department),
            ("job", state.JobTitle));
        DwaineStatus.Text = state.DwaineAvailable
            ? Loc.GetString("nano-xp-dwaine-available")
            : Loc.GetString("nano-xp-dwaine-unavailable");
        LaunchDwaineButton.Disabled = !state.DwaineAvailable;

        if (!state.Authenticated)
            ShowView(DesktopView);
    }

    private void SubmitLogin()
    {
        OnLoginRequested?.Invoke(AddressInput.Text, PasswordInput.Text);
        PasswordInput.Text = string.Empty;
    }

    private void SubmitEnrollment()
    {
        OnEnrollRequested?.Invoke(PasswordInput.Text);
        PasswordInput.Text = string.Empty;
    }

    private void SubmitMail()
    {
        var body = Rope.Collapse(BodyInput.TextRope);
        OnMailRequested?.Invoke(RecipientInput.Text, SubjectInput.Text, body);
        SubjectInput.Text = string.Empty;
        BodyInput.TextRope = Rope.Leaf.Empty;
    }

    private void PopulateInbox(IReadOnlyList<NanoXpMailEntry> inbox)
    {
        Inbox.Clear();
        MailSender.Text = Loc.GetString("nano-xp-mail-no-selection");
        MailSubject.Text = string.Empty;
        MailBody.SetMessage(FormattedMessage.Empty);
        foreach (var mail in inbox)
        {
            Inbox.AddItem(
                Loc.GetString("nano-xp-mail-entry", ("sender", mail.Sender), ("subject", mail.Subject)),
                metadata: mail);
        }
    }

    private void PopulateDirectory(IReadOnlyList<NanoXpDirectoryEntry> directory)
    {
        Directory.Clear();
        foreach (var entry in directory)
        {
            Directory.AddItem(
                Loc.GetString(
                    "nano-xp-directory-entry",
                    ("name", entry.DisplayName),
                    ("address", entry.Address),
                    ("department", entry.Department)),
                selectable: false);
        }
    }

    private void OnMailSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (args.ItemList[args.ItemIndex].Metadata is not NanoXpMailEntry mail)
            return;

        MailSender.Text = Loc.GetString("nano-xp-mail-from", ("sender", mail.Sender));
        MailSubject.Text = mail.Subject;
        MailBody.SetMessage(FormattedMessage.FromUnformatted(mail.Body));
    }

    private void ShowView(Control view)
    {
        DesktopView.Visible = ReferenceEquals(view, DesktopView);
        MailView.Visible = ReferenceEquals(view, MailView);
        DepartmentView.Visible = ReferenceEquals(view, DepartmentView);
        BrowserView.Visible = ReferenceEquals(view, BrowserView);
        DwaineView.Visible = ReferenceEquals(view, DwaineView);
    }

    private string NoticeText(NanoXpNotice notice)
        => notice == NanoXpNotice.None
            ? string.Empty
            : Loc.GetString(notice switch
            {
                NanoXpNotice.Enrolled => "nano-xp-notice-enrolled",
                NanoXpNotice.LoggedIn => "nano-xp-notice-logged-in",
                NanoXpNotice.LoggedOut => "nano-xp-notice-logged-out",
                NanoXpNotice.IdentityRequired => "nano-xp-notice-identity-required",
                NanoXpNotice.AccessDenied => "nano-xp-notice-access-denied",
                NanoXpNotice.InvalidMail => "nano-xp-notice-invalid-mail",
                NanoXpNotice.UnknownRecipient => "nano-xp-notice-unknown-recipient",
                NanoXpNotice.MailboxFull => "nano-xp-notice-mailbox-full",
                NanoXpNotice.MailSent => "nano-xp-notice-mail-sent",
                NanoXpNotice.RateLimited => "nano-xp-notice-rate-limited",
                NanoXpNotice.Offline => "nano-xp-notice-offline",
                _ => "nano-xp-notice-invalid-credential",
            });
}
