// SPDX-FileCopyrightText: 2026 Whiskey Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Whiskey.Dwaine;
using Content.Shared._Whiskey.Dwaine.Hardware;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Whiskey.Dwaine.Hardware;

[GenerateTypedNameReferences]
public sealed partial class DwaineTerminalWindow : DefaultWindow
{
    public event Action? OnPowerRequested;
    public event Action<string>? OnInputSubmitted;

    public DwaineTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        Power.OnPressed += _ => OnPowerRequested?.Invoke();
        Send.OnPressed += _ => SubmitInput();
        Input.OnTextEntered += _ => SubmitInput();
    }

    public void UpdateState(DwaineTerminalBoundUserInterfaceState state)
    {
        Status.Text = Loc.GetString(state.Status switch
        {
            DwaineHardwareStatus.PoweredOff => "dwaine-terminal-status-powered-off",
            DwaineHardwareStatus.PowerUnavailable => "dwaine-terminal-status-power-unavailable",
            DwaineHardwareStatus.HardwareReady => "dwaine-terminal-status-hardware-ready",
            _ => "dwaine-terminal-status-power-unavailable",
        });

        Display.Text = Loc.GetString("dwaine-terminal-display-value",
            ("columns", state.DisplayColumns),
            ("rows", state.DisplayRows));
        Connectors.Text = Loc.GetString("dwaine-terminal-connectors-value",
            ("storage", state.StorageSlots),
            ("network", string.IsNullOrEmpty(state.NetworkId) ? "-" : state.NetworkId),
            ("bus", string.IsNullOrEmpty(state.BusId) ? "-" : state.BusId));
        Output.Text = string.Join('\n', state.Output);

        var ready = state.Status == DwaineHardwareStatus.HardwareReady;
        Input.Editable = ready;
        Send.Disabled = !ready;
    }

    private void SubmitInput()
    {
        var text = Input.Text;
        if (string.IsNullOrEmpty(text))
            return;

        OnInputSubmitted?.Invoke(text);
        Input.Text = string.Empty;
    }
}
