// SPDX-FileCopyrightText: 2026 Whiskey Station Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Whiskey.Dwaine;
using Content.Shared._Whiskey.Dwaine.Hardware;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Whiskey.Dwaine.Hardware;

[GenerateTypedNameReferences]
public sealed partial class DwaineTerminalWindow : DefaultWindow
{
    public event Action? OnPowerRequested;
    public event Action<string>? OnInputSubmitted;
    public event Action<NetEntity>? OnConnectRequested;
    public event Action? OnDisconnectRequested;

    private readonly Dictionary<int, NetEntity> _mainframeTargets = new();
    private NetEntity? _selectedMainframe;

    public DwaineTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        Power.OnPressed += _ => OnPowerRequested?.Invoke();
        Send.OnPressed += _ => SubmitInput();
        Input.OnTextEntered += _ => SubmitInput();
        Mainframes.OnItemSelected += args =>
        {
            Mainframes.SelectId(args.Id);
            if (_mainframeTargets.TryGetValue(args.Id, out var target))
                _selectedMainframe = target;
        };
        Connect.OnPressed += _ =>
        {
            if (_selectedMainframe is { } target)
                OnConnectRequested?.Invoke(target);
        };
        Disconnect.OnPressed += _ => OnDisconnectRequested?.Invoke();
    }

    public void UpdateState(DwaineTerminalBoundUserInterfaceState state)
    {
        Status.Text = Loc.GetString(state.Status switch
        {
            DwaineHardwareStatus.PoweredOff => "dwaine-terminal-status-powered-off",
            DwaineHardwareStatus.PowerUnavailable => "dwaine-terminal-status-power-unavailable",
            DwaineHardwareStatus.HardwareReady => "dwaine-terminal-status-hardware-ready",
            _ => "dwaine-terminal-status-power-unavailable",
        });

        Display.Text = Loc.GetString("dwaine-terminal-display-value",
            ("columns", state.DisplayColumns),
            ("rows", state.DisplayRows));
        Connectors.Text = Loc.GetString("dwaine-terminal-connectors-value",
            ("storage", state.StorageSlots),
            ("network", string.IsNullOrEmpty(state.NetworkId) ? "-" : state.NetworkId),
            ("bus", string.IsNullOrEmpty(state.BusId) ? "-" : state.BusId));
        Output.Text = string.Join('\n', state.Output);

        Connection.Text = Loc.GetString(state.ConnectionStatus switch
        {
            DwaineTerminalConnectionStatus.Disconnected => "dwaine-terminal-connection-disconnected",
            DwaineTerminalConnectionStatus.Connected => "dwaine-terminal-connection-connected",
            DwaineTerminalConnectionStatus.MainframeUnavailable => "dwaine-terminal-connection-unavailable",
            _ => "dwaine-terminal-connection-disconnected",
        }, ("mainframe", state.ConnectedMainframe));

        var previousTarget = _selectedMainframe;
        _selectedMainframe = null;
        _mainframeTargets.Clear();
        Mainframes.Clear();
        for (var index = 0; index < state.AvailableMainframes.Length; index++)
        {
            var entry = state.AvailableMainframes[index];
            _mainframeTargets.Add(index, entry.Entity);
            Mainframes.AddItem(entry.Name, index);
            if (previousTarget == entry.Entity)
            {
                Mainframes.SelectId(index);
                _selectedMainframe = entry.Entity;
            }
        }

        if (_selectedMainframe is null && state.AvailableMainframes.Length > 0)
        {
            Mainframes.SelectId(0);
            _selectedMainframe = state.AvailableMainframes[0].Entity;
        }

        var connected = state.ConnectionStatus == DwaineTerminalConnectionStatus.Connected;
        var ready = state.Status == DwaineHardwareStatus.HardwareReady && connected;
        Input.Editable = ready;
        Send.Disabled = !ready;
        Mainframes.Disabled = connected || state.AvailableMainframes.Length == 0;
        Connect.Disabled = connected || _selectedMainframe is null;
        Disconnect.Disabled = !connected;
    }

    private void SubmitInput()
    {
        var text = Input.Text;
        if (string.IsNullOrEmpty(text))
            return;

        OnInputSubmitted?.Invoke(text);
        Input.Text = string.Empty;
    }
}
